FROM nocobase/nocobase:main
ARG LOCAL_STORAGE_BASE_URL=/storage/uploads

# Bundle app source
#COPY . /app/nocobas
COPY . .

EXPOSE 80


# echo iu461750 | docker login -u 183461750@qq.com --password-stdin registry.cn-hangzhou.aliyuncs.com

# docker build -t nocobase:v1-fa .

# docker tag nocobase:v1-fa registry.cn-hangzhou.aliyuncs.com/fa/nocobase:v1-fa
# docker push registry.cn-hangzhou.aliyuncs.com/fa/nocobase:v1-fa
